# Generated by Django 3.1.4 on 2021-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_hire', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admission',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly',
            field=models.FloatField(null=True),
        ),
    ]
