# Generated by Django 3.1.4 on 2021-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_hire', '0007_auto_20210530_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='initials',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
